/*
 * Jake Lawrence
 * December 3, 2015
 * Medway HS
 * VHS
 */


import java.util.*;
import java.util.Random;

public class GuessNum{
    public static void main(String[] args){
        
        Scanner console = new Scanner(System.in);
        
        System.out.print("To have the computer guess your number, enter \"computer\". ");
        System.out.print("To guess a number 1-100 generated by the the computer, enter \"number\": ");
        
        String uIn = console.nextLine();
        
        
        while(!(uIn.toUpperCase().equals("COMPUTER")) && !(uIn.toUpperCase().equals("NUMBER"))){
         System.out.println("\"" + uIn + "\" is not a valid entry.");
         System.out.print("To have the computer guess your number, enter \"computer\"");
            System.out.print("To guess a number 1-100 generated by the the computer, enter \"number\": ");
            uIn = console.nextLine();
        }
        
        if(uIn.toUpperCase().equals("COMPUTER")){
         cGuess();
        }else if(uIn.toUpperCase().equals("NUMBER")){
         uGuess();
        }
        
    }
    
    public static void uGuess(){
     Scanner console = new Scanner(System.in);
     
     Random generator = new Random();
        
        int x = generator.nextInt(100) + 1;
        
        System.out.print("I'm thinking of a number 1-100; take a guess: ");
        int y = console.nextInt();
        
        int count = 1;
        
        while(y != x){
            if(x > y){
                System.out.print("My number was higher. Try again: ");
                y = console.nextInt();
            }else{
                System.out.print("My number was lower. Try again: ");
                y = console.nextInt();
            }
            count++;
        }
        System.out.println("Nice job! You guessed it! My number was " + x + "! It took you " + count + " guesses!");
    }
    
    public static void cGuess(){
     Scanner console = new Scanner(System.in);
     
     Random generator = new Random();
        
        int x = generator.nextInt(100) + 1;
        int max = 100;
        int min = 0;
        
        System.out.print("Enter a number 1-100, for the computer to guess: ");
        int y = console.nextInt();
        while(y < 0 || y > 100){
         System.out.print(y + "is not between 1-100, enter your number again: ");
         y = console.nextInt();
        }
        
        int count = 1;
        
        while(y != x){
         System.out.println("The computer's guess #" + count + "  was: " + x);
            if(x > y){
             max = x;
                
            }else{
             min = x;
            }
            x = (max +  min + 1) / 2;
            count++;
        }
        System.out.println("The computer guessed your number, " + y + ", in "+ count +" tries!");

    }
}